#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : gtksourceview
Version  : 4.0.0
Release  : 20
URL      : https://download.gnome.org/sources/gtksourceview/4.0/gtksourceview-4.0.0.tar.xz
Source0  : https://download.gnome.org/sources/gtksourceview/4.0/gtksourceview-4.0.0.tar.xz
Summary  : Libraries and include files for GtkSourceView
Group    : Development/Tools
License  : LGPL-2.1
Requires: gtksourceview-data
Requires: gtksourceview-lib
Requires: gtksourceview-doc
Requires: gtksourceview-locales
BuildRequires : docbook-xml
BuildRequires : gettext
BuildRequires : go
BuildRequires : gobject-introspection
BuildRequires : gobject-introspection-dev
BuildRequires : gtk-doc
BuildRequires : gtk-doc-dev
BuildRequires : itstool
BuildRequires : libxslt-bin
BuildRequires : meson
BuildRequires : ninja
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(gio-2.0)
BuildRequires : pkgconfig(glib-2.0)
BuildRequires : pkgconfig(gtk+-3.0)
BuildRequires : pkgconfig(libxml-2.0)
BuildRequires : python3
BuildRequires : vala
BuildRequires : valgrind
Patch1: cve-2017-14108.patch

%description
GtkSourceview is a library that adds syntax highlighting,
line numbers, and other programming-editor features.
GtkSourceView specializes these features for a code editor.

%package data
Summary: data components for the gtksourceview package.
Group: Data

%description data
data components for the gtksourceview package.


%package dev
Summary: dev components for the gtksourceview package.
Group: Development
Requires: gtksourceview-lib
Requires: gtksourceview-data
Provides: gtksourceview-devel

%description dev
dev components for the gtksourceview package.


%package doc
Summary: doc components for the gtksourceview package.
Group: Documentation

%description doc
doc components for the gtksourceview package.


%package lib
Summary: lib components for the gtksourceview package.
Group: Libraries
Requires: gtksourceview-data

%description lib
lib components for the gtksourceview package.


%package locales
Summary: locales components for the gtksourceview package.
Group: Default

%description locales
locales components for the gtksourceview package.


%prep
%setup -q -n gtksourceview-4.0.0
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1523379482
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
export FCFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
export FFLAGS="$CFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
export CXXFLAGS="$CXXFLAGS -O3 -Os -fdata-sections -ffat-lto-objects -ffunction-sections -flto=4 -fno-semantic-interposition -fstack-protector-strong -mzero-caller-saved-regs "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check || :

%install
export SOURCE_DATE_EPOCH=1523379482
rm -rf %{buildroot}
%make_install
%find_lang gtksourceview-4

%files
%defattr(-,root,root,-)

%files data
%defattr(-,root,root,-)
/usr/lib64/girepository-1.0/GtkSource-4.typelib
/usr/share/gir-1.0/*.gir
/usr/share/gtksourceview-4/language-specs/R.lang
/usr/share/gtksourceview-4/language-specs/abnf.lang
/usr/share/gtksourceview-4/language-specs/actionscript.lang
/usr/share/gtksourceview-4/language-specs/ada.lang
/usr/share/gtksourceview-4/language-specs/ansforth94.lang
/usr/share/gtksourceview-4/language-specs/asp.lang
/usr/share/gtksourceview-4/language-specs/automake.lang
/usr/share/gtksourceview-4/language-specs/awk.lang
/usr/share/gtksourceview-4/language-specs/bennugd.lang
/usr/share/gtksourceview-4/language-specs/bibtex.lang
/usr/share/gtksourceview-4/language-specs/bluespec.lang
/usr/share/gtksourceview-4/language-specs/boo.lang
/usr/share/gtksourceview-4/language-specs/c.lang
/usr/share/gtksourceview-4/language-specs/cg.lang
/usr/share/gtksourceview-4/language-specs/changelog.lang
/usr/share/gtksourceview-4/language-specs/chdr.lang
/usr/share/gtksourceview-4/language-specs/cmake.lang
/usr/share/gtksourceview-4/language-specs/cobol.lang
/usr/share/gtksourceview-4/language-specs/cpp.lang
/usr/share/gtksourceview-4/language-specs/cpphdr.lang
/usr/share/gtksourceview-4/language-specs/csharp.lang
/usr/share/gtksourceview-4/language-specs/css.lang
/usr/share/gtksourceview-4/language-specs/csv.lang
/usr/share/gtksourceview-4/language-specs/cuda.lang
/usr/share/gtksourceview-4/language-specs/d.lang
/usr/share/gtksourceview-4/language-specs/def.lang
/usr/share/gtksourceview-4/language-specs/desktop.lang
/usr/share/gtksourceview-4/language-specs/diff.lang
/usr/share/gtksourceview-4/language-specs/docbook.lang
/usr/share/gtksourceview-4/language-specs/dosbatch.lang
/usr/share/gtksourceview-4/language-specs/dot.lang
/usr/share/gtksourceview-4/language-specs/dpatch.lang
/usr/share/gtksourceview-4/language-specs/dtd.lang
/usr/share/gtksourceview-4/language-specs/dtl.lang
/usr/share/gtksourceview-4/language-specs/eiffel.lang
/usr/share/gtksourceview-4/language-specs/erlang.lang
/usr/share/gtksourceview-4/language-specs/fcl.lang
/usr/share/gtksourceview-4/language-specs/forth.lang
/usr/share/gtksourceview-4/language-specs/fortran.lang
/usr/share/gtksourceview-4/language-specs/fsharp.lang
/usr/share/gtksourceview-4/language-specs/gap.lang
/usr/share/gtksourceview-4/language-specs/gdb-log.lang
/usr/share/gtksourceview-4/language-specs/genie.lang
/usr/share/gtksourceview-4/language-specs/glsl.lang
/usr/share/gtksourceview-4/language-specs/go.lang
/usr/share/gtksourceview-4/language-specs/groovy.lang
/usr/share/gtksourceview-4/language-specs/gtk-doc.lang
/usr/share/gtksourceview-4/language-specs/gtkrc.lang
/usr/share/gtksourceview-4/language-specs/haddock.lang
/usr/share/gtksourceview-4/language-specs/haskell-literate.lang
/usr/share/gtksourceview-4/language-specs/haskell.lang
/usr/share/gtksourceview-4/language-specs/haxe.lang
/usr/share/gtksourceview-4/language-specs/html.lang
/usr/share/gtksourceview-4/language-specs/idl-exelis.lang
/usr/share/gtksourceview-4/language-specs/idl.lang
/usr/share/gtksourceview-4/language-specs/imagej.lang
/usr/share/gtksourceview-4/language-specs/ini.lang
/usr/share/gtksourceview-4/language-specs/j.lang
/usr/share/gtksourceview-4/language-specs/jade.lang
/usr/share/gtksourceview-4/language-specs/java.lang
/usr/share/gtksourceview-4/language-specs/javascript.lang
/usr/share/gtksourceview-4/language-specs/json.lang
/usr/share/gtksourceview-4/language-specs/julia.lang
/usr/share/gtksourceview-4/language-specs/kotlin.lang
/usr/share/gtksourceview-4/language-specs/language.dtd
/usr/share/gtksourceview-4/language-specs/language.rng
/usr/share/gtksourceview-4/language-specs/language2.rng
/usr/share/gtksourceview-4/language-specs/latex.lang
/usr/share/gtksourceview-4/language-specs/lex.lang
/usr/share/gtksourceview-4/language-specs/libtool.lang
/usr/share/gtksourceview-4/language-specs/llvm.lang
/usr/share/gtksourceview-4/language-specs/logcat.lang
/usr/share/gtksourceview-4/language-specs/lua.lang
/usr/share/gtksourceview-4/language-specs/m4.lang
/usr/share/gtksourceview-4/language-specs/makefile.lang
/usr/share/gtksourceview-4/language-specs/mallard.lang
/usr/share/gtksourceview-4/language-specs/markdown.lang
/usr/share/gtksourceview-4/language-specs/matlab.lang
/usr/share/gtksourceview-4/language-specs/maxima.lang
/usr/share/gtksourceview-4/language-specs/mediawiki.lang
/usr/share/gtksourceview-4/language-specs/meson.lang
/usr/share/gtksourceview-4/language-specs/modelica.lang
/usr/share/gtksourceview-4/language-specs/mxml.lang
/usr/share/gtksourceview-4/language-specs/nemerle.lang
/usr/share/gtksourceview-4/language-specs/netrexx.lang
/usr/share/gtksourceview-4/language-specs/nsis.lang
/usr/share/gtksourceview-4/language-specs/objc.lang
/usr/share/gtksourceview-4/language-specs/objj.lang
/usr/share/gtksourceview-4/language-specs/ocaml.lang
/usr/share/gtksourceview-4/language-specs/ocl.lang
/usr/share/gtksourceview-4/language-specs/octave.lang
/usr/share/gtksourceview-4/language-specs/ooc.lang
/usr/share/gtksourceview-4/language-specs/opal.lang
/usr/share/gtksourceview-4/language-specs/opencl.lang
/usr/share/gtksourceview-4/language-specs/pascal.lang
/usr/share/gtksourceview-4/language-specs/perl.lang
/usr/share/gtksourceview-4/language-specs/php.lang
/usr/share/gtksourceview-4/language-specs/pig.lang
/usr/share/gtksourceview-4/language-specs/pkgconfig.lang
/usr/share/gtksourceview-4/language-specs/po.lang
/usr/share/gtksourceview-4/language-specs/prolog.lang
/usr/share/gtksourceview-4/language-specs/protobuf.lang
/usr/share/gtksourceview-4/language-specs/puppet.lang
/usr/share/gtksourceview-4/language-specs/python.lang
/usr/share/gtksourceview-4/language-specs/python3.lang
/usr/share/gtksourceview-4/language-specs/rpmspec.lang
/usr/share/gtksourceview-4/language-specs/rst.lang
/usr/share/gtksourceview-4/language-specs/ruby.lang
/usr/share/gtksourceview-4/language-specs/rust.lang
/usr/share/gtksourceview-4/language-specs/scala.lang
/usr/share/gtksourceview-4/language-specs/scheme.lang
/usr/share/gtksourceview-4/language-specs/scilab.lang
/usr/share/gtksourceview-4/language-specs/sh.lang
/usr/share/gtksourceview-4/language-specs/sml.lang
/usr/share/gtksourceview-4/language-specs/sparql.lang
/usr/share/gtksourceview-4/language-specs/sql.lang
/usr/share/gtksourceview-4/language-specs/sweave.lang
/usr/share/gtksourceview-4/language-specs/swift.lang
/usr/share/gtksourceview-4/language-specs/systemverilog.lang
/usr/share/gtksourceview-4/language-specs/t2t.lang
/usr/share/gtksourceview-4/language-specs/tcl.lang
/usr/share/gtksourceview-4/language-specs/tera.lang
/usr/share/gtksourceview-4/language-specs/texinfo.lang
/usr/share/gtksourceview-4/language-specs/thrift.lang
/usr/share/gtksourceview-4/language-specs/vala.lang
/usr/share/gtksourceview-4/language-specs/vbnet.lang
/usr/share/gtksourceview-4/language-specs/verilog.lang
/usr/share/gtksourceview-4/language-specs/vhdl.lang
/usr/share/gtksourceview-4/language-specs/xml.lang
/usr/share/gtksourceview-4/language-specs/xslt.lang
/usr/share/gtksourceview-4/language-specs/yacc.lang
/usr/share/gtksourceview-4/language-specs/yaml.lang
/usr/share/gtksourceview-4/styles/classic.xml
/usr/share/gtksourceview-4/styles/cobalt.xml
/usr/share/gtksourceview-4/styles/kate.xml
/usr/share/gtksourceview-4/styles/oblivion.xml
/usr/share/gtksourceview-4/styles/solarized-dark.xml
/usr/share/gtksourceview-4/styles/solarized-light.xml
/usr/share/gtksourceview-4/styles/styles.rng
/usr/share/gtksourceview-4/styles/tango.xml

%files dev
%defattr(-,root,root,-)
/usr/include/gtksourceview-4/gtksourceview/completion-providers/words/gtksourcecompletionwords.h
/usr/include/gtksourceview-4/gtksourceview/gtksource-enumtypes.h
/usr/include/gtksourceview-4/gtksourceview/gtksource.h
/usr/include/gtksourceview-4/gtksourceview/gtksourceautocleanups.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcebuffer.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcecompletion.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcecompletioncontext.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcecompletioninfo.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcecompletionitem.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcecompletionproposal.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcecompletionprovider.h
/usr/include/gtksourceview-4/gtksourceview/gtksourceencoding.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcefile.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcefileloader.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcefilesaver.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcegutter.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcegutterrenderer.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcegutterrendererpixbuf.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcegutterrenderertext.h
/usr/include/gtksourceview-4/gtksourceview/gtksourceinit.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcelanguage.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcelanguagemanager.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcemap.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcemark.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcemarkattributes.h
/usr/include/gtksourceview-4/gtksourceview/gtksourceprintcompositor.h
/usr/include/gtksourceview-4/gtksourceview/gtksourceregion.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcesearchcontext.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcesearchsettings.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcespacedrawer.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcestyle.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcestylescheme.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcestyleschemechooser.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcestyleschemechooserbutton.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcestyleschemechooserwidget.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcestyleschememanager.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcetag.h
/usr/include/gtksourceview-4/gtksourceview/gtksourcetypes.h
/usr/include/gtksourceview-4/gtksourceview/gtksourceundomanager.h
/usr/include/gtksourceview-4/gtksourceview/gtksourceutils.h
/usr/include/gtksourceview-4/gtksourceview/gtksourceversion.h
/usr/include/gtksourceview-4/gtksourceview/gtksourceview.h
/usr/lib64/libgtksourceview-4.so
/usr/lib64/pkgconfig/gtksourceview-4.pc

%files doc
%defattr(-,root,root,-)
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceBuffer.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceCompletion.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceCompletionContext.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceCompletionInfo.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceCompletionItem.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceCompletionProposal.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceCompletionProvider.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceCompletionWords.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceEncoding.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceFile.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceFileLoader.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceFileSaver.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceGutter.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceGutterRenderer.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceGutterRendererPixbuf.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceGutterRendererText.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceLanguage.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceLanguageManager.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceMap.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceMark.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceMarkAttributes.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourcePrintCompositor.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceRegion.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceSearchContext.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceSearchSettings.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceSpaceDrawer.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceStyle.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceStyleScheme.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceStyleSchemeChooser.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceStyleSchemeChooserButton.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceStyleSchemeChooserWidget.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceStyleSchemeManager.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceTag.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceUndoManager.html
/usr/share/gtk-doc/html/gtksourceview-4.0/GtkSourceView.html
/usr/share/gtk-doc/html/gtksourceview-4.0/annexes.html
/usr/share/gtk-doc/html/gtksourceview-4.0/annotation-glossary.html
/usr/share/gtk-doc/html/gtksourceview-4.0/api-index-full.html
/usr/share/gtk-doc/html/gtksourceview-4.0/api-reference.html
/usr/share/gtk-doc/html/gtksourceview-4.0/completion.html
/usr/share/gtk-doc/html/gtksourceview-4.0/file-loading-and-saving.html
/usr/share/gtk-doc/html/gtksourceview-4.0/general.html
/usr/share/gtk-doc/html/gtksourceview-4.0/gtksourceview-4.0-GtkSourceUtils.html
/usr/share/gtk-doc/html/gtksourceview-4.0/gtksourceview-4.0-GtkSourceView-Initialization-and-Finalization.html
/usr/share/gtk-doc/html/gtksourceview-4.0/gtksourceview-4.0-Version-Information.html
/usr/share/gtk-doc/html/gtksourceview-4.0/gtksourceview-4.0.devhelp2
/usr/share/gtk-doc/html/gtksourceview-4.0/gutter.html
/usr/share/gtk-doc/html/gtksourceview-4.0/home.png
/usr/share/gtk-doc/html/gtksourceview-4.0/index.html
/usr/share/gtk-doc/html/gtksourceview-4.0/intro.html
/usr/share/gtk-doc/html/gtksourceview-4.0/lang-reference.html
/usr/share/gtk-doc/html/gtksourceview-4.0/lang-tutorial.html
/usr/share/gtk-doc/html/gtksourceview-4.0/left-insensitive.png
/usr/share/gtk-doc/html/gtksourceview-4.0/left.png
/usr/share/gtk-doc/html/gtksourceview-4.0/main-classes.html
/usr/share/gtk-doc/html/gtksourceview-4.0/misc.html
/usr/share/gtk-doc/html/gtksourceview-4.0/object-tree.html
/usr/share/gtk-doc/html/gtksourceview-4.0/porting-guide-3-to-4.html
/usr/share/gtk-doc/html/gtksourceview-4.0/porting-guide.html
/usr/share/gtk-doc/html/gtksourceview-4.0/printing.html
/usr/share/gtk-doc/html/gtksourceview-4.0/right-insensitive.png
/usr/share/gtk-doc/html/gtksourceview-4.0/right.png
/usr/share/gtk-doc/html/gtksourceview-4.0/search-and-replace.html
/usr/share/gtk-doc/html/gtksourceview-4.0/style-reference.html
/usr/share/gtk-doc/html/gtksourceview-4.0/style.css
/usr/share/gtk-doc/html/gtksourceview-4.0/styling.html
/usr/share/gtk-doc/html/gtksourceview-4.0/syntax-highlighting-reference.html
/usr/share/gtk-doc/html/gtksourceview-4.0/syntax-highlighting.html
/usr/share/gtk-doc/html/gtksourceview-4.0/up-insensitive.png
/usr/share/gtk-doc/html/gtksourceview-4.0/up.png

%files lib
%defattr(-,root,root,-)
/usr/lib64/libgtksourceview-4.so.0
/usr/lib64/libgtksourceview-4.so.0.0.0

%files locales -f gtksourceview-4.lang
%defattr(-,root,root,-)

